language: ruby
rvm:
  - 2.2.2
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test CODECLIMATE_REPO_TOKEN=ffbbb90d205e7b2a0df13e6cd785c7cf2b08b9031e9b0516dc6164bfc56bd2bf bundle exec rspec
